import type { Metadata } from "next";
import { geistSans, geistMono } from '@/app/components/font';
import ThemeProvider from '@/app/context/theme-context';
import "@/app/globals.css";

export const metadata: Metadata = {
	title: "HabitSync",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
                <ThemeProvider>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
